### ISSUE TITLE
Error with np.random.choice

### ISSUE THREAD

**Issue by itsmeshreyans** [dyelax/Adversarial_Video_Generation#26]
Traceback (most recent call last):
  File "avg_runner.py", line 185, in <module>
    main()
  File "avg_runner.py", line 181, in main
    runner.train()
  File "avg_runner.py", line 68, in train
    batch = get_train_batch()
  File "/Users/shreyans/Desktop/Hamburg_Assignments/Neural networks/version 2/Adversarial_Video_Generation/Code/utils.py", line 126, in get_train_batch
    path = c.TRAIN_DIR_CLIPS + str(np.random.choice(c.NUM_CLIPS)) + '.npz'
  File "mtrand.pyx", line 1120, in mtrand.RandomState.choice
ValueError: a must be greater than 0

**Comment by smilefenglei** [comment]
@itsmeshreyans Have you solve it? I met the same question with you.

**Comment by gefeiwang** [comment]
I got the same error when I was running process_data.py.

**Comment by stillbetter** [comment]
You need to make sure the dataset in the right directory.


---Original---

**Comment by gefeiwang** [comment]
@stillbetter Thank you! I got this problem solved, and I can run avg_runner.py without normally after processing data.
