### ISSUE TITLE
Unable to reproduce results on Pacman dataset

### ISSUE THREAD

**Issue by akileshbadrinaaraayanan** [dyelax/Adversarial_Video_Generation#6]
Hi Matt,

I am trying to reproduce your results on Pacman dataset. When running the pre-process step, I am getting the following warnings: "Overflow encountered in square", "Invalid value encountered in subtract" in line 53 of utils.py ( diff += np.sum(np.square(next_frame - frame))). I am working with the master branch. When I tried:  print(np.amax(frame) and  print(np.amax(next_frame)) in clip_l2_diff function, the values are as high as 9.91442958312e+230. In addition, there are some nans too. 

Is there an issue with the Pacman dataset itself?

**Comment by dyelax** [comment]
There shouldn't be any issues with the Pacman dataset, but you may want to check that your OS hasn't created any hidden files in there that the program might be grabbing and trying to interpret as images (Mac OS will sometimes do this). It could also be a problem with newer TensorFlow versions, since this hasn't been updated in a while.

Hopefully I'll have a chance to get back to this project and clean it all up sometime soon, but I just started a new job, so not sure when I'll have the time to get around to it.

**Comment by deckyal** [comment]
Hi, I am trying to reproduce the results using the pretrained model. But it gives me errors : 

python avg_runner.py -l ./Models/Adversarial/model.ckp
t-500000 -t ./Data/Test
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Init discriminator...
Init generator...
Init variables...
Traceback (most recent call last):
  File "avg_runner.py", line 185, in <module>
    main()
  File "avg_runner.py", line 177, in main
    runner = AVGRunner(num_steps, load_path, num_test_rec)
  File "avg_runner.py", line 58, in __init__
    self.saver.restore(self.sess, model_load_path)
  File "/home/deckyal/anaconda2/envs/NormalEnv/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1428, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/deckyal/anaconda2/envs/NormalEnv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/deckyal/anaconda2/envs/NormalEnv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/deckyal/anaconda2/envs/NormalEnv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/deckyal/anaconda2/envs/NormalEnv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "generator/scale_3/setup/Variable_9/optimizer_1" not found in checkpoint files ./Models/Adversarial/model.ckpt-500000
	 [[Node: save/RestoreV2_166 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_166/tensor_names, save/RestoreV2_166/shape_and_slices)]]

Caused by op u'save/RestoreV2_166', defined at:
  File "avg_runner.py", line 185, in <module>
    main()
  File "avg_runner.py", line 177, in main
    runner = AVGRunner(num_steps, load_path, num_test_rec)
  File "avg_runner.py", line 53, in __init__
    self.saver = tf.train.Saver(keep_checkpoint_every_n_hours=2)
  File "/home/deckyal/anaconda2/envs/NormalEnv/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1040, in __init__
    self.build()
  File "/home/deckyal/anaconda2/envs/NormalEnv/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1070, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/deckyal/anaconda2/envs/NormalEnv/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 675, in build
    restore_sequentially, reshape)
  File "/home/deckyal/anaconda2/envs/NormalEnv/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 402, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/deckyal/anaconda2/envs/NormalEnv/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 242, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/deckyal/anaconda2/envs/NormalEnv/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 668, in restore_v2
    dtypes=dtypes, name=name)
  File "/home/deckyal/anaconda2/envs/NormalEnv/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/deckyal/anaconda2/envs/NormalEnv/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/deckyal/anaconda2/envs/NormalEnv/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Tensor name "generator/scale_3/setup/Variable_9/optimizer_1" not found in checkpoint files ./Models/Adversarial/model.ckpt-500000
	 [[Node: save/RestoreV2_166 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_166/tensor_names, save/RestoreV2_166/shape_and_slices)]]

**Comment by newuhe** [comment]
@deckyal  I have the same question,what's wrong with it? Do you fix it?

**Comment by dyelax** [comment]
@deckyal Which version of TensorFlow are you using? This only works for up to version 0.12 currently.
